### PR TITLE
Update swagger client and models to service-broker v1.124.0

### PR DESCRIPTION
**Pull request by powervs-ibm**
This pull request includes generated client and model files from service-broker commit fe82d2c9fa0339d5975dce2d229c3ab7e30c32f6

### CODE REVIEW

**Comment by yussufsh** [comment]
@michaelkad can we have the service broker version in the commit message as well?

**Comment by yussufsh** [comment]
It will be helpful while listing commits on UI or cli. Or else we have to look for the PR no. and see the release information of service broker. 
If it is difficult to add via the automation then it's fine by me to not add in commit as well.

**Comment by michaelkad** [comment]
> It will be helpful while listing commits on UI or cli. Or else we have to look for the PR no. and see the release information of service broker.
> If it is difficult to add via the automation then it's fine by me to not add in commit as well.

@yussufsh by service broker version  you meant this ` v1.124.0` ?
Since we the version and the commit hash, both can be used to look that release info using the link below. 
https://github.ibm.com/power-iaas/service-broker/releases/tag/{version}
https://github.ibm.com/power-iaas/service-broker/commit/{commit hash}

 I could add a link to SB release info if that is what you are referring to. https://github.ibm.com/power-iaas/service-broker/releases/tag/v1.124.0

**Comment by yussufsh** [comment]
No, just the version string as in the pr is enough. We should not link internal urls here.

**Review by yussufsh — APPROVED** [review]
lgtm

**Comment by michaelkad** [comment]
> No, just the version string as in the pr is enough. We should not link internal urls here.

@yussufsh Okay, I will add that.

**Comment by michaelkad** [comment]
@yussufsh @johnnguyen3196 @rmoralesjr @dhirendersingh19 
An important aspect to consider is that multiple Pull Requests (PRs) may be created during a sprint if a Swagger change is detected in the SB Swagger file. The version of SB used would be the version from the previous/current production push.
Also, CLI will depend on it.

This approach provides flexibility in choosing which changes to merge, especially when aiming to deliver a feature within the same sprint. Here's my suggested approach for merging:

1. We prioritize merging generated files when a feature requires those changes during the same sprint. This allows us to quickly address feature-specific updates and streamline the development process.

1. Towards the end of the sprint, we conduct a comprehensive merge that aligns with the SB production push. This ensures that all relevant changes are incorporated into the main codebase and prepares it for deployment.

By adopting this approach, we optimize our development efforts, enabling us to focus on delivering features efficiently while maintaining stability through regular end-of-sprint merges. This strategy strikes a balance between rapid development and maintaining a coherent codebase, ultimately enhancing our productivity and the overall quality of our software delivery.

Feel free to share your thoughts on this proposed approach.

**Comment by yussufsh** [comment]
I would suggest generating such PRs only on new tags from Service Broker, which ensures the code is part of production environment. If a developer needs a tag he should be able to trigger the automation from Travis which will pick the latest commit OR manually generate the clients using the swagger file.
We should not merge in between commits as that won't work for the production users.

**Comment by yussufsh** [comment]
@michaelkad suggest creating an [issue](https://github.com/IBM-Cloud/power-go-client/issue) to further discuss the process. This one will be merged in.

**Pull request merged**
