### PR TITLE
Code fix in the cloudconnection delete

### PR DESCRIPTION
**Pull request by mkumatag**
Fixes: #85

### CODE REVIEW

**Review by surajsub — COMMENTED** [review]
What is the reason for the change ?

**Comment by mkumatag** [comment]
> What is the reason for the change ?

I have mentioned the reason here in the #85 , its throwing SIGSEGV

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x160e2f5]

goroutine 74 [running]:
testing.tRunner.func1.1(0x255d660, 0x3578a60)
	/usr/local/Cellar/go/1.15.7/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000603980)
	/usr/local/Cellar/go/1.15.7/libexec/src/testing/testing.go:1075 +0x41a
panic(0x255d660, 0x3578a60)
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/panic.go:969 +0x1b9
github.com/IBM-Cloud/power-go-client/clients/instance.(*IBMPICloudConnectionClient).Delete(0xc000bc95c0, 0x27c4007, 0x24, 0xc000284fc0, 0x24, 0x1, 0x0, 0x9a, 0x0)
	/Users/manjunath/openshift_ws/src/github.com/openshift/cluster-api-provider-powervs/vendor/github.com/IBM-Cloud/power-go-client/clients/instance/ibm-pi-cloud-connection.go:91 +0x1d5
github.com/openshift/cluster-api-provider-powervs/pkg/client.TestFormatProviderID(0xc000603980)
	/Users/manjunath/openshift_ws/src/github.com/openshift/cluster-api-provider-powervs/pkg/client/f1_test.go:45 +0x3b8
testing.tRunner(0xc000603980, 0x287ebe0)
	/usr/local/Cellar/go/1.15.7/libexec/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/Cellar/go/1.15.7/libexec/src/testing/testing.go:1168 +0x2b3


Process finished with the exit code 1
```

**Review by surajsub — APPROVED** [review]

**Comment by mkumatag** [comment]
@surajsub can we merge this PR?

**Pull request merged**
