### PR TITLE
 Add hostgroups

### PR DESCRIPTION
**Pull request by michaelkad**
Adding Hostgroups functions. Some of the endpoints are still in progress, just getting ahead start on it.

### CODE REVIEW

**Comment by yussufsh** [comment]
You can convert it to draft if WIP
image

**Comment by michaelkad** [comment]
> You can convert it to draft if WIP image

@yussufsh We already possess  the Swagger definitions for those endpoints, so it seems prudent to commence the work now and defer functional testing for later.

And since we are on this topic, you have made some of those changes. why aren't we directly invoking `power/client` from Terraform? Instead, we seem to be duplicating efforts by implementing those functions within `clients/instance`. This approach appears redundant to me, and I'm seeking clarity on whether there was or is a requirement to proceed in this manner.

**Comment by yussufsh** [comment]
> @yussufsh We already possess the Swagger definitions for those endpoints, so it seems prudent to commence the work now and defer functional testing for later.

The description says `Some of the endpoints are still in progress`. Better mark the PR as WIP or draft. Getting ahead of the production environment and sometimes unknowingly merging these types of PRs creates additional work.
 
> And since we are on this topic, you have made some of those changes. why aren't we directly invoking `power/client` from Terraform? Instead, we seem to be duplicating efforts by implementing those functions within `clients/instance`. This approach appears redundant to me, and I'm seeking clarity on whether there was or is a requirement to proceed in this manner.

It has been the same since the beginning (before I joined). The client is responsible for maintaining the session, validating the request parameters and responses, etc. Also, this layer helps in any additional processing required before making an API request to the service.

Without this layer, there is no use for this project. Anyone can download the production swagger file and use it in his project (Terraform) to create the stub directly. We are making their life easy by implementing a standard way to make the resource calls and other aspects like auth, validations, etc.

**Comment by michaelkad** [comment]
> The description says Some of the endpoints are still in progress. Better mark the PR as WIP or draft. Getting ahead of the production environment and sometimes unknowingly merging these types of PRs creates additional work.

It appears we would have to be working along side staging moving forward, hence having those up before staging and creating prod releases when it is GA. All the in-between release will be marked v1.x.x-dev, with this the additional work would be to create a new release which I believe is not much work.

>It has been the same since the beginning (before I joined). The client is responsible for maintaining the session, validating the request parameters and responses, etc. Also, this layer helps in any additional processing required before making an API request to the service.

>Without this layer, there is no use for this project. Anyone can download the production swagger file and use it in his project (Terraform) to create the stub directly. We are making their life easy by implementing a standard way to make the resource calls and other aspects like auth, validations, etc.

Fair points.

**Review by Diptipowervs — APPROVED** [review]

**Review by ismirlia — APPROVED** [review]

**Pull request merged**
